alias: doors_interior_garage_opened
trigger:
  platform: state
  entity_id: binary_sensor.garage_interior_door_contact
  to: 'on'
action:
  service: notify.discord_general
  data:
    message: "Interior garage door opened!"
    target: [!secret discord_channel_id_entry]