title: DnA Home
views:
  - title: Home
    panel: false
    icon: mdi:home
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: thermostat
        entity: climate.family_room
      - type: glance
        entities:
          - entity: sensor.dan_commute_to_work
            name: Dan's Commute
            tap_action:
              action: call-service
              service: notify.discord_general
              service_data:
                message: |
                  {{ states('input_text.discord_user_dan') }}
                  travel time
                      {{ states('sensor.dan_commute_to_work') }} minutes
                  route
                      {{ state_attr('sensor.dan_commute_to_work', 'route') }}
                target: [!secret discord_channel_id_commute]
          - entity: sensor.ash_commute_to_work
            name: Ashly's Commute
            tap_action:
              action: call-service
              service: notify.discord_general
              service_data:
                message: |
                  {{ states('input_text.discord_user_ash') }}
                  travel time
                      {{ states('sensor.ash_commute_to_work') }} minutes
                  route
                      {{ state_attr('sensor.ash_commute_to_work', 'route') }}
                target: [!secret discord_channel_id_commute]
      - type: glance
        entities:
          - entity: binary_sensor.master_poop_closet_nightlight
            name: Master Bath Nightlight
          - entity: light.espresso_machine_rgb_switch
            name: Espresso Machine
            icon: mdi:coffee
          - entity: switch.front_house_light_switch
            name: Front House Lights
            icon: mdi:lightbulb
            tap_action:
              action: toggle
          - entity: binary_sensor.garage_interior_door_contact
            name: Garage Door
      - type: vertical-stack
        title: Temperature
        cards:
          - type: sensor
            entity: sensor.dark_sky_apparent_temperature
            name: Outside
            graph: line
          - type: sensor
            entity: sensor.family_room_thermostat_temperature
            name: Inside
            graph: line
      - type: vertical-stack
        title: Humidity
        cards:
          - type: sensor
            entity: sensor.dark_sky_humidity
            name: Outside
            graph: line
          - type: sensor
            entity: sensor.game_room_multisensor_humidity
            name: Inside
            graph: line

  - title: Temperature, Humidity, and Weather
    panel: false
    icon: mdi:thermometer-lines
    cards:
      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - entity: sensor.dark_sky_temperature
            name: Temperature
          - entity: sensor.dark_sky_apparent_temperature
            name: Feels Like
          - entity: sensor.dark_sky_daytime_high_temperature_0d
            name: Today's High
          - entity: sensor.dark_sky_daytime_high_apparent_temperature_0d
            name: Today's Feels Like High
          - entity: sensor.dark_sky_overnight_low_temperature_0d
            name: Tonight's Low
          - entity: sensor.dark_sky_overnight_low_apparent_temperature_0d
            name: Tonight's Feels Like Low
          - entity: sensor.dark_sky_humidity
            name: humidity
          - entity: sensor.dark_sky_precip_probability
            name: Precipitation Chance
            icon: mdi:weather-snowy-rainy
          - entity: sensor.dark_sky_cloud_coverage
            name: Clood Coverage
          - entity: sensor.dark_sky_wind_speed
            name: Wind Speed
          - entity: sensor.dark_sky_wind_gust
            name: Gusts
      - type: vertical-stack
        title: 'Temperature'
        cards:
          - type: history-graph
            title: 'Inside Temperature'
            refresh_interval: 600
            entities:
              - entity: sensor.game_room_multisensor_temperature
                name: Game Room
              - entity: sensor.family_room_multisensor_temperature
                name: Family Room
              - entity: sensor.master_bath_multisensor_temperature
                name: Master Bath
              - entity: sensor.family_room_thermostat_temperature
                name: Nest
          - type: history-graph
            title: 'Outside Temperature'
            refresh_interval: 600
            entities:
              - entity: sensor.dark_sky_temperature
                name: Dark Sky
      - type: vertical-stack
        title: 'Humidity'
        cards:
          - type: history-graph
            title: 'Inside Humidity'
            refresh_interval: 600
            entities:
              - entity: sensor.game_room_multisensor_humidity
                name: Game Room
              - entity: sensor.family_room_multisensor_humidity
                name: Family Room
              - entity: sensor.master_bath_multisensor_humidity
                name: Master Bath
              - entity: sensor.family_room_thermostat_humidity
                name: Nest
          - type: history-graph
            title: 'Outside Humidity'
            refresh_interval: 600
            entities:
              - entity: sensor.dark_sky_humidity
                name: Dark Sky

  - title: Automations
    panel: false
    icon: mdi:engine
    cards:
      - type: entities
        title: Master Bath
        show_header_toggle: false
        entities:
          - automation.poop_closet_daylight_setup
          - automation.poop_closet_nightlight_setup
          - automation.poop_closet_nightlight_on
          - automation.poop_closet_nightlight_off
          - automation.poop_closet_nightlight_override_switch_turn_off
      - type: entities
        title: House Lights
        show_header_toggle: false
        entities:
          - automation.house_front_nightlight_setup
          - automation.house_front_nightlight_disable
      - type: entities
        title: Espresso Machine
        show_header_toggle: false
        entities:
          - automation.espresso_machine_morning_coffee_on
          - automation.espresso_machine_morning_coffee_off
      - type: entities
        title: Notifications
        show_header_toggle: false
        entities:
          - automation.doors_interior_garage_opened
          - automation.poop_closet_nightlight_turned_on
          - automation.poop_closet_nightlight_turned_off
  
  - title: System
    panel: false
    icon: mdi:raspberry-pi
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Current
            entities:
              - entity: sensor.disk_use_percent_home
                name: Disk
              - entity: sensor.memory_use_percent
                name: Memory
              - entity: sensor.processor_use
                name: Processor
              - entity: sensor.last_boot_date
                name: Last Boot
                format: datetime
          - type: history-graph
            title: History
            entities:
              - entity: sensor.memory_use_percent
                name: Memory
              - entity: sensor.processor_use
                name: Processor
            refresh_interval: 600
            hours_to_show: 6

  - title: Ash
    panel: false
    cards:
      - type: entities
        title: Monday
        show_header_toggle: false
        entities:
          - input_boolean.ash_working_mon
          - input_datetime.ash_comehome_mon
      - type: entities
        title: Tuesday
        show_header_toggle: false
        entities:
          - input_boolean.ash_working_tues
          - input_datetime.ash_comehome_tues
      - type: entities
        title: Wednesday
        show_header_toggle: false
        entities:
          - input_boolean.ash_working_wed
          - input_datetime.ash_comehome_wed
      - type: entities
        title: Thursday
        show_header_toggle: false
        entities:
          - input_boolean.ash_working_thurs
          - input_datetime.ash_comehome_thurs
      - type: entities
        title: Friday
        show_header_toggle: false
        entities:
          - input_boolean.ash_working_fri
          - input_datetime.ash_comehome_fri
  
  - title: Dan
    panel: false
    cards:
      - type: entities
        title: Commute
        show_header_toggle: false
        entities:
          - sensor.dan_commute_to_work
          - sensor.dan_commute_to_home

  - title: Test
    panel: false
    icon: mdi:test-tube
    cards:
      - type: glance
        entities:
          - entity: binary_sensor.bedtime
            name: Bedtime
            icon: mdi:sleep
          - entity: binary_sensor.coffeetime
            name: Coffeetime
            icon: mdi:coffee
          - entity: binary_sensor.worktime
            name: Worktime
            icon: mdi:worker
          - entity: binary_sensor.playtime
            name: Playtime
            icon: mdi:party-popper
          - entity: binary_sensor.work_week
            name: Work Week
            icon: mdi:worker
          - entity: binary_sensor.master_bath_too_humid
            name: Master Bath Too Humid
            icon: mdi:water-percent
          - entity: binary_sensor.workday_ash
            name: Ash Workday
            icon: mdi:worker
          - entity: binary_sensor.probably_commuting_ash
            name: Ash commuting
            icon: mdi:car-hatchback
          - entity: binary_sensor.probably_commuting_dan
            name: Dan commuting
            icon: mdi:car-sports
          - entity: input_datetime.ash_comehome_time
            name: Ash Commute Start
          - entity: input_boolean.home_from_work_ash
            name: Ash Home From Work
          - entity: input_boolean.home_from_work_dan
            name: Dan Home From Work
      - type: glance
        entities:
          - climate.family_room
          - binary_sensor.family_room_thermostat_fan
          - binary_sensor.family_room_thermostat_has_leaf
          - binary_sensor.family_room_thermostat_is_locked
          - binary_sensor.family_room_thermostat_is_using_emergency_heat
          - binary_sensor.family_room_thermostat_online
          - sensor.family_room_thermostat_humidity
          - sensor.family_room_thermostat_hvac_state
          - sensor.family_room_thermostat_operation_mode
          - sensor.family_room_thermostat_target
          - sensor.family_room_thermostat_temperature
      - type: glance
        entities:
          - binary_sensor.family_room_multisensor_contact
          - binary_sensor.game_room_multisensor_contact
          - binary_sensor.master_bath_multisensor_contact
      - type: history-graph
        title: Espresso Machine Power
        entities:
          - entity: sensor.espresso_machine_power_8
            name: Watts
        refresh_interval: 600
        hours_to_show: 24
      - type: entities
        title: Switches
        entities:
          - switch.front_house_light_switch
          - switch.poop_closet_light_switch
          - switch.master_bath_fan_switch