title: DnA Home
views:
  - title: Home
    panel: false
    icon: mdi:home
    cards:
      - type: sensor
        entity: sensor.dark_sky_apparent_temperature
        name: Outside Temp
        graph: line
      - type: sensor
        entity: sensor.family_room_thermostat_temperature
        name: Inside Temp
        graph: line
      - type: gauge
        entity: sensor.aeotec_zw100_multisensor_6_relative_humidity_2
        name: Inside Humidity
      - type: gauge
        entity: sensor.dark_sky_humidity
        name: Outside Humidity
      - type: glance
        entities:
          - entity: binary_sensor.master_poop_closet_nightlight
            name: Master Bath Nightlight
          - entity: switch.aeotec_zw096_smart_switch_6_switch
            name: Espresso Machine
            icon: mdi:coffee
            tap_action:
              action: toggle
          - entity: switch.homeseer_hs_ws200_wall_switch_switch_2
            name: Front House Lights
            icon: mdi:lightbulb
            tap_action:
              action: toggle
          - entity: binary_sensor.aeotec_zw112_door_window_sensor_6_sensor
            name: Garage Door

  - title: Temperature, Humidity, and Weather
    panel: false
    icon: mdi:thermometer-lines
    cards:
      - type: thermostat
        entity: climate.family_room
      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - entity: sensor.dark_sky_temperature
            name: Temperature
          - entity: sensor.dark_sky_apparent_temperature
            name: Feels Like
          - entity: sensor.dark_sky_daytime_high_temperature_0d
            name: Today's High
          - entity: sensor.dark_sky_daytime_high_apparent_temperature_0d
            name: Today's Feels Like High
          - entity: sensor.dark_sky_overnight_low_temperature_0d
            name: Tonight's Low
          - entity: sensor.dark_sky_overnight_low_apparent_temperature_0d
            name: Tonight's Feels Like Low
          - entity: sensor.dark_sky_humidity
            name: humidity
          - entity: sensor.dark_sky_precip_probability
            name: Precipitation Chance
            icon: mdi:weather-snowy-rainy
          - entity: sensor.dark_sky_cloud_coverage
            name: Clood Coverage
          - entity: sensor.dark_sky_wind_speed
            name: Wind Speed
          - entity: sensor.dark_sky_wind_gust
            name: Gusts
      - type: history-graph
        title: 'Temperature'
        entities:
          - entity: sensor.aeotec_zw100_multisensor_6_temperature
            name: Master Bath
          - entity: sensor.aeotec_zw100_multisensor_6_temperature_2
            name: Family Room
          - entity: sensor.family_room_thermostat_temperature
            name: Nest
          - entity: sensor.dark_sky_temperature
            name: Dark Sky
        refresh_interval: 600
      - type: history-graph
        title: 'Humidity'
        entities:
          - entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
            name: Master Bath
          - entity: sensor.aeotec_zw100_multisensor_6_relative_humidity_2
            name: Family Room
          - entity: sensor.family_room_thermostat_humidity
            name: Nest
          - entity: sensor.dark_sky_humidity
            name: Dark Sky
        refresh_interval: 600

  - title: Automations
    panel: false
    icon: mdi:engine
    cards:
      - type: entities
        title: Master Bath
        show_header_toggle: false
        entities:
          - automation.poop_closet_daylight_setup
          - automation.poop_closet_nightlight_setup
          - automation.poop_closet_nightlight_on
          - automation.poop_closet_nightlight_off
          - automation.poop_closet_nightlight_override_switch_turn_off
      - type: entities
        title: House Lights
        show_header_toggle: false
        entities:
          - automation.house_front_nightlight_setup
          - automation.house_front_nightlight_disable
      - type: entities
        title: Espresso Machine
        show_header_toggle: false
        entities:
          - automation.espresso_machine_morning_coffee_on
          - automation.espresso_machine_morning_coffee_off_week
          - automation.espresso_machine_morning_coffee_off_weekend
      - type: entities
        title: Notifications
        show_header_toggle: false
        entities:
          - automation.doors_notify_discord
  
  - title: System
    panel: false
    icon: mdi:raspberry-pi
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Current
            entities:
              - entity: sensor.disk_use_percent_home
                name: Disk
              - entity: sensor.memory_use_percent
                name: Memory
              - entity: sensor.processor_use
                name: Processor
              - entity: sensor.last_boot_date
                name: Last Boot
                format: datetime
          - type: history-graph
            title: History
            entities:
              - entity: sensor.memory_use_percent
                name: Memory
              - entity: sensor.processor_use
                name: Processor
            refresh_interval: 600
            hours_to_show: 6
  - title: Test
    panel: false
    icon: mdi:test-tube
    cards:
      - type: glance
        entities:
          - entity: binary_sensor.bedtime
            name: Bedtime
            icon: mdi:sleep
          - entity: binary_sensor.worktime
            name: Worktime
            icon: mdi:worker
          - entity: binary_sensor.playtime
            name: Playtime
            icon: mdi:party-popper