alias: espresso_machine_morning_coffee_off
trigger:
  platform: state
  entity_id: binary_sensor.coffeetime
  to: 'off'
action:
  - service: switch.turn_off
    entity_id: switch.aeotec_zw096_smart_switch_6_switch