alias: espresso_machine_morning_coffee_off
trigger:
  platform: state
  entity_id: binary_sensor.coffeetime
  to: 'off'
action:
  - service: light.turn_off
    entity_id: light.espresso_machine_rgb_switch