alias: espresso_machine_morning_coffee_on
trigger:
  platform: state
  entity_id: binary_sensor.coffeetime
  to: 'on'
action:
  - service: light.turn_on
    entity_id: light.espresso_machine_rgb_switch