alias: people_just_got_home_ash
trigger:
  platform: state
  entity_id: binary_sensor.garage_interior_door_contact
  to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.probably_commuting_ash
    state: 'on'
  - condition: state
    entity_id: input_boolean.home_from_work_ash
    state: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home_from_work_ash
  - service: notify.discord_general
    data:
      message: |
          {{ states('input_text.discord_user_everyone') }}
          It looks like Ashly just got home!
      target: [!secret discord_channel_id_general]