alias: people_output_dan_commute_to_home
initial_state: 'on'
trigger:
  - platform: time
    at: "14:45:00"
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: homeassistant.update_entity
    entity_id: sensor.dan_commute_to_home
  - service: notify.discord_general
    data_template:
      message: |
        {{ states('input_text.discord_user_dan') }}
        __**Afternoon Commute**__
        >>> 
            travel time
                `{{ states('sensor.dan_commute_to_home') }} minutes`
            route
                `{{ state_attr('sensor.dan_commute_to_home', 'route') }}`
      target: [!secret discord_channel_id_commute]