alias: people_output_dan_commute_to_work
initial_state: 'on'
trigger:
  - platform: time_pattern
    minutes: '/15'
condition:
  - condition: time
    after: '05:30:00'
    before: '06:30:00'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: homeassistant.update_entity
    entity_id: sensor.dan_commute_to_work
  - service: notify.discord_general
    data_template:
      message: |
        {{ states('input_text.discord_user_dan') }}
        __**Morning Commute**__
        >>> 
            travel time
                `{{ states('sensor.dan_commute_to_work') }} minutes`
            route
                `{{ state_attr('sensor.dan_commute_to_work', 'route') }}`
      target: [!secret discord_channel_id_commute]