alias: poop_closet_daylight_setup
trigger:
  - platform: time
    at: '05:15'
  - event_type: zwave.scene_activated
    platform: event
    event_data:
      entity_id: zwave.homeseer_hs_ws200_wall_switch
      scene_id: 1
      scene_data: 7860
action:
  - service: switch.turn_on
    entity_id: switch.homeseer_hs_ws200_wall_switch_switch
  - service: homeassistant.turn_on
    data:
      entity_id: group.poop_closet_lights
      kelvin: 5000
      brightness_pct: 60
  - service: switch.turn_off
    entity_id: switch.homeseer_hs_ws200_wall_switch_switch