alias: poop_closet_nightlight_off
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'off'
    for: '00:01:30'
  - platform: state
    entity_id: binary_sensor.master_poop_closet_nightlight
    to: 'on'
condition:
  condition: time
  after: '20:00:00'
  before: '05:15:00'
action:
  - service: homeassistant.turn_off
    entity_id: group.poop_closet_lights