alias: poop_closet_nightlight_turned_off
trigger:
  platform: state
  entity_id: binary_sensor.master_poop_closet_nightlight
  to: 'off'
action:
  - service: notify.discord_general
    data:
      message: "Master bathroom nightlight off."
      target: [!secret discord_channel_id_scheduled_automations]
