alias: poop_closet_nightlight_override_switch_turn_off
trigger:
  platform: state
  entity_id: switch.homeseer_technologies_hs_ws200_wall_switch_switch
  to: 'off'
  for: '00:00:01'
condition:
  condition: state
  entity_id: binary_sensor.bedtime
  state: 'on'
action:
  service: switch.turn_on
  entity_id: switch.homeseer_technologies_hs_ws200_wall_switch_switch