alias: poop_closet_nightlight_off
trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'off'
    for: '00:02:00'
  - platform: state
    entity_id: binary_sensor.master_poop_closet_nightlight
    to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.bedtime
  state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: group.poop_closet_lights