alias: poop_closet_nightlight_setup
trigger:
  - platform: state
    entity_id: binary_sensor.bedtime
    to: 'on'
  - event_type: zwave.scene_activated
    platform: event
    event_data:
      entity_id: zwave.homeseer_technologies_hs_ws200_wall_switch
      scene_id: 2
      scene_data: 7860
action:
  - service: switch.turn_on
    entity_id: switch.homeseer_technologies_hs_ws200_wall_switch_switch
  - service: homeassistant.turn_on
    data:
      entity_id: group.poop_closet_lights
      rgb_color: [255, 0, 0]
      brightness_pct: 30