alias: poop_closet_nightlight_on
trigger:
  platform: state
  entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
  to: 'on'
condition:
  condition: time
  after: '20:00:00'
  before: '05:15:00'
action:
  - service: homeassistant.turn_on
    entity_id: group.poop_closet_lights