alias: poop_closet_nightlight_on
trigger:
  platform: state
  entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
  to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.bedtime
  state: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: group.poop_closet_lights