alias: poop_closet_nightlight_override_switch_turn_off
trigger:
  platform: state
  entity_id: switch.homeseer_technologies_hs_ws200_wall_switch_switch
  to: 'off'
  for: '00:00:01'
condition:
  condition: time
  after: '20:00:10'
  before: '05:15:00'
action:
  service: switch.turn_on
  entity_id: switch.homeseer_technologies_hs_ws200_wall_switch_switch