alias: master_bath_too_humid
trigger:
  platform: state
  entity_id: binary_sensor.master_bath_too_humid
  to: 'on'
  from: 'off'
action:
  - service: notify.discord_general
    data:
      message: "It's getting humid in here!"
      target: [!secret discord_channel_id_automations]
  - condition: state
    entity_id: switch.master_bath_fan_switch
    state: 'off'
  - service: notify.discord_general
    data:
      message: "Somebody turn the vent on!"
      target: [!secret discord_channel_id_automations]
  - service: switch.turn_on
    entity_id: switch.master_bath_fan_switch