alias: home_assistant_morning_report
initial_state: 'on'
trigger:
  - platform: time
    at: "05:30:00"
action:
  service: notify.discord_general
  data_template:
    message: |
      {{ states('input_text.discord_user_everyone') }}
      __**Morning Report**__
      >>> 
          **weather forecast**
              `{{ states('sensor.dark_sky_hourly_summary') }}`
              
          **today's high**
              `{{ states('sensor.dark_sky_daytime_high_apparent_temperature_0d') }}{{ state_attr('sensor.dark_sky_daytime_high_apparent_temperature_0d', 'unit_of_measurement') }}`
          **tonight's low**
              `{{ states('sensor.dark_sky_overnight_low_apparent_temperature_0d') }}{{ state_attr('sensor.dark_sky_overnight_low_apparent_temperature_0d', 'unit_of_measurement') }}`
          **precipitation chance**
              `{{ states('sensor.dark_sky_precip_probability_0d') }}{{ state_attr('sensor.dark_sky_precip_probability_0d', 'unit_of_measurement') }}`
    target: [!secret discord_channel_id_general]