alias: house_front_nightlight_disable
trigger:
  platform: sun
  event: sunrise
action:
  - service: switch.turn_off
    entity_id: switch.front_house_light_switch
  - service: notify.discord_general
    data:
      message: "House front lights off."
      target: [!secret discord_channel_id_scheduled_automations]