alias: house_front_nightlight_setup
trigger:
  platform: sun
  event: sunset
action:
  - service: switch.turn_on
    entity_id: switch.homeseer_hs_ws200_wall_switch_switch_2
  - service: notify.discord_general
    data:
      message: "House front lights on."
      target: [!secret discord_channel_id_scheduled_automations]