alias: house_front_nightlight_setup
trigger:
  platform: sun
  event: sunset
action:
  - service: switch.turn_on
    entity_id: switch.front_house_light_switch
  - service: notify.discord_general
    data:
      message: "House front lights on."
      target: [!secret discord_channel_id_scheduled_automations]